name: Release

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Tagged Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release ${{ github.ref_name }}
          prerelease: false
          make_latest: true
          files: |
            new_openstack_host_setup.sh
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update Canary Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: canary
          name: Canary Build
          body: Latest development build from commit ${{ github.sha }}
          prerelease: true
          make_latest: false
          target_commitish: ${{ github.sha }}
          files: |
            new_openstack_host_setup.sh
          token: ${{ secrets.GITHUB_TOKEN }}