name: Release

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine release type
        id: release_type
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "type=tag" >> $GITHUB_OUTPUT
            echo "name=${TAG_NAME}" >> $GITHUB_OUTPUT
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "type=canary" >> $GITHUB_OUTPUT
            echo "name=canary" >> $GITHUB_OUTPUT
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi

      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_type.outputs.name }}
          name: ${{ steps.release_type.outputs.type == 'tag' && format('Release {0}', steps.release_type.outputs.name) || 'Canary Build' }}
          body: ${{ steps.release_type.outputs.type == 'tag' && format('Release {0}', steps.release_type.outputs.name) || format('Latest development build from commit {0}', github.sha) }}
          prerelease: ${{ steps.release_type.outputs.type == 'canary' }}
          make_latest: ${{ steps.release_type.outputs.is_latest }}
          files: |
            new_openstack_host_setup.sh
          token: ${{ secrets.GITHUB_TOKEN }}