on:
  push:
    tags: ['*.*.*']
  release:
    types: [published]

jobs:
  release-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: new_openstack_host_setup.sh
          fail_on_unmatched_files: true

  release-on-ui:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: new_openstack_host_setup.sh
          fail_on_unmatched_files: true
