name: Release
on:
  push:
    branches: [main]
    tags: ['[0-9]+\\.[0-9]+\\.[0-9]+.*']  # semver tags
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Create a GitHub Release for version tags
      - name: Create Tagged Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release ${{ github.ref_name }}
          prerelease: false
          files: new_openstack_host_setup.sh
          token: ${{ secrets.GITHUB_TOKEN }}
